In [1]:
import acquire as acq
import os 
import pandas as pd
from sklearn.model_selection import train_test_split
import prepare as prep
#directory
directory = os.getcwd()

In [2]:
prep.get_prep_split_iris()

(     sepal_length  sepal_width  petal_length  petal_width     species  \
 70            5.9          3.2           4.8          1.8  versicolor
 123           6.3          2.7           4.9          1.8   virginica
 87            6.3          2.3           4.4          1.3  versicolor
 3             4.6          3.1           1.5          0.2      setosa
 15            5.7          4.4           1.5          0.4      setosa
 ..            ...          ...           ...          ...         ...
 11            4.8          3.4           1.6          0.2      setosa
 29            4.7          3.2           1.6          0.2      setosa
 96            5.7          2.9           4.2          1.3  versicolor
 44            5.1          3.8           1.9          0.4      setosa
 97            6.2          2.9           4.3          1.3  versicolor

      species_versicolor  species_virginica
 70                    1                  0
 123                   0                  1
 87                    1                  0
 3                     0                  0
 15                    0                  0
 ..                  ...                ...
 11                    0                  0
 29                    0                  0
 96                    1                  0
 44                    0                  0
 97                    1                  0

 [90 rows x 7 columns],
      sepal_length  sepal_width  petal_length  petal_width     species  \
 124           6.7          3.3           5.7          2.1   virginica
 62            6.0          2.2           4.0          1.0  versicolor
 122           7.7          2.8           6.7          2.0   virginica
 98            5.1          2.5           3.0          1.1  versicolor
 64            5.6          2.9           3.6          1.3  versicolor
 60            5.0          2.0           3.5          1.0  versicolor
 136           6.3          3.4           5.6          2.4   virginica
 39            5.1          3.4           1.5          0.2      setosa
 27            5.2          3.5           1.5          0.2      setosa
 13            4.3          3.0           1.1          0.1      setosa
 99            5.7          2.8           4.1          1.3  versicolor
 90            5.5          2.6           4.4          1.2  versicolor
 121           5.6          2.8           4.9          2.0   virginica
 10            5.4          3.7           1.5          0.2      setosa
 47            4.6          3.2           1.4          0.2      setosa
 143           6.8          3.2           5.9          2.3   virginica
 21            5.1          3.7           1.5          0.4      setosa
 66            5.6          3.0           4.5          1.5  versicolor
 78            6.0          2.9           4.5          1.5  versicolor
 148           6.2          3.4           5.4          2.3   virginica
 113           5.7          2.5           5.0          2.0   virginica
 75            6.6          3.0           4.4          1.4  versicolor
 37            4.9          3.6           1.4          0.1      setosa
 49            5.0          3.3           1.4          0.2      setosa
 134           6.1          2.6           5.6          1.4   virginica
 106           4.9          2.5           4.5          1.7   virginica
 102           7.1          3.0           5.9          2.1   virginica
 71            6.1          2.8           4.0          1.3  versicolor
 30            4.8          3.1           1.6          0.2      setosa
 0             5.1          3.5           1.4          0.2      setosa

      species_versicolor  species_virginica
 124                   0                  1
 62                    1                  0
 122                   0                  1
 98                    1                  0
 64                    1                  0
 60                    1                  0
 136                   0                  1
 39                    0                  0
 27                    0                  0
 13                    0                  0
 99                    1                  0
 90                    1                  0
 121                   0                  1
 10                    0                  0
 47                    0                  0
 143                   0                  1
 21                    0                  0
 66                    1                  0
 78                    1                  0
 148                   0                  1
 113                   0                  1
 75                    1                  0
 37                    0                  0
 49                    0                  0
 134                   0                  1
 106                   0                  1
 102                   0                  1
 71                    1                  0
 30                    0                  0
 0                     0                  0  ,
      sepal_length  sepal_width  petal_length  petal_width     species  \
 80            5.5          2.4           3.8          1.1  versicolor
 45            4.8          3.0           1.4          0.3      setosa
 144           6.7          3.3           5.7          2.5   virginica
 110           6.5          3.2           5.1          2.0   virginica
 38            4.4          3.0           1.3          0.2      setosa
 2             4.7          3.2           1.3          0.2      setosa
 135           7.7          3.0           6.1          2.3   virginica
 72            6.3          2.5           4.9          1.5  versicolor
 138           6.0          3.0           4.8          1.8   virginica
 34            4.9          3.1           1.5          0.2      setosa
 19            5.1          3.8           1.5          0.3      setosa
 77            6.7          3.0           5.0          1.7  versicolor
 101           5.8          2.7           5.1          1.9   virginica
 63            6.1          2.9           4.7          1.4  versicolor
 117           7.7          3.8           6.7          2.2   virginica
 76            6.8          2.8           4.8          1.4  versicolor
 42            4.4          3.2           1.3          0.2      setosa
 22            4.6          3.6           1.0          0.2      setosa
 28            5.2          3.4           1.4          0.2      setosa
 33            5.5          4.2           1.4          0.2      setosa
 17            5.1          3.5           1.4          0.3      setosa
 116           6.5          3.0           5.5          1.8   virginica
 127           6.1          3.0           4.9          1.8   virginica
 56            6.3          3.3           4.7          1.6  versicolor
 105           7.6          3.0           6.6          2.1   virginica
 146           6.3          2.5           5.0          1.9   virginica
 93            5.0          2.3           3.3          1.0  versicolor
 86            6.7          3.1           4.7          1.5  versicolor
 68            6.2          2.2           4.5          1.5  versicolor
 65            6.7          3.1           4.4          1.4  versicolor

      species_versicolor  species_virginica
 80                    1                  0
 45                    0                  0
 144                   0                  1
 110                   0                  1
 38                    0                  0
 2                     0                  0
 135                   0                  1
 72                    1                  0
 138                   0                  1
 34                    0                  0
 19                    0                  0
 77                    1                  0
 101                   0                  1
 63                    1                  0
 117                   0                  1
 76                    1                  0
 42                    0                  0
 22                    0                  0
 28                    0                  0
 33                    0                  0
 17                    0                  0
 116                   0                  1
 127                   0                  1
 56                    1                  0
 105                   0                  1
 146                   0                  1
 93                    1                  0
 86                    1                  0
 68                    1                  0
 65                    1                  0  )

In [3]:
prep.get_prep_split_telco()

(      gender  senior_citizen partner dependents  tenure phone_service  \
 5911    Male               0      No        Yes      26            No
 2479  Female               0     Yes         No      47           Yes
 5889  Female               0      No         No       1           Yes
 6087    Male               0      No         No      69            No
 785   Female               0      No         No      51           Yes
 ...      ...             ...     ...        ...     ...           ...
 6102  Female               0     Yes         No       2           Yes
 356   Female               1      No         No      52            No
 1756    Male               0      No         No       4           Yes
 2127    Male               0      No         No      35           Yes
 3586  Female               0      No         No      10           Yes

      multiple_lines online_security online_backup device_protection  ...  \
 5911             No              No           Yes                No  ...
 2479            Yes              No            No                No  ...
 5889             No              No            No               Yes  ...
 6087             No             Yes           Yes                No  ...
 785              No              No            No                No  ...
 ...             ...             ...           ...               ...  ...
 6102             No              No           Yes               Yes  ...
 356              No              No           Yes               Yes  ...
 1756             No              No            No                No  ...
 2127            Yes             Yes            No                No  ...
 3586             No              No           Yes                No  ...

      online_security_Yes online_backup_Yes device_protection_Yes  \
 5911                   0                 1                     0
 2479                   0                 0                     0
 5889                   0                 0                     1
 6087                   1                 1                     0
 785                    0                 0                     0
 ...                  ...               ...                   ...
 6102                   0                 1                     1
 356                    0                 1                     1
 1756                   0                 0                     0
 2127                   1                 0                     0
 3586                   0                 1                     0

      streaming_tv_Yes  paperless_billing_Yes  \
 5911                1                      1
 2479                0                      0
 5889                0                      1
 6087                1                      1
 785                 1                      0
 ...               ...                    ...
 6102                0                      0
 356                 1                      1
 1756                0                      1
 2127                0                      0
 3586                0                      0

      internet_service_type_Fiber optic internet_service_type_None  \
 5911                                 0                          0
 2479                                 0                          1
 5889                                 0                          0
 6087                                 0                          0
 785                                  1                          0
 ...                                ...                        ...
 6102                                 1                          0
 356                                  0                          0
 1756                                 1                          0
 2127                                 0                          0
 3586                                 0                          0

      payment_type_Credit card (automatic) payment_type_Electronic check  \
 5911                                    0                             0
 2479                                    0                             1
 5889                                    0                             0
 6087                                    0                             0
 785                                     1                             0
 ...                                   ...                           ...
 6102                                    0                             0
 356                                     0                             1
 1756                                    0                             1
 2127                                    0                             0
 3586                                    0                             0

      payment_type_Mailed check
 5911                         0
 2479                         0
 5889                         1
 6087                         0
 785                          0
 ...                        ...
 6102                         0
 356                          0
 1756                         0
 2127                         1
 3586                         1

 [4225 rows x 36 columns],
       gender  senior_citizen partner dependents  tenure phone_service  \
 3554  Female               0      No         No      56           Yes
 2063  Female               0      No         No      67           Yes
 1737    Male               1     Yes         No      17           Yes
 5894  Female               0     Yes        Yes      45           Yes
 209   Female               1     Yes         No      68           Yes
 ...      ...             ...     ...        ...     ...           ...
 2529  Female               1     Yes         No      14           Yes
 6540    Male               0     Yes        Yes      13           Yes
 5765    Male               0     Yes         No      72           Yes
 6959  Female               0      No        Yes      34           Yes
 3108  Female               0     Yes         No      61           Yes

      multiple_lines online_security online_backup device_protection  ...  \
 3554            Yes              No           Yes               Yes  ...
 2063             No             Yes           Yes                No  ...
 1737             No              No           Yes                No  ...
 5894            Yes              No            No                No  ...
 209             Yes              No           Yes                No  ...
 ...             ...             ...           ...               ...  ...
 2529            Yes              No           Yes                No  ...
 6540            Yes              No            No                No  ...
 5765            Yes              No           Yes               Yes  ...
 6959             No             Yes            No               Yes  ...
 3108            Yes              No            No                No  ...

      online_security_Yes online_backup_Yes device_protection_Yes  \
 3554                   0                 1                     1
 2063                   1                 1                     0
 1737                   0                 1                     0
 5894                   0                 0                     0
 209                    0                 1                     0
 ...                  ...               ...                   ...
 2529                   0                 1                     0
 6540                   0                 0                     0
 5765                   0                 1                     1
 6959                   1                 0                     1
 3108                   0                 0                     0

      streaming_tv_Yes  paperless_billing_Yes  \
 3554                1                      1
 2063                0                      0
 1737                0                      1
 5894                0                      1
 209                 1                      1
 ...               ...                    ...
 2529                1                      1
 6540                0                      1
 5765                1                      1
 6959                1                      0
 3108                1                      0

      internet_service_type_Fiber optic internet_service_type_None  \
 3554                                 1                          0
 2063                                 0                          0
 1737                                 1                          0
 5894                                 0                          1
 209                                  1                          0
 ...                                ...                        ...
 2529                                 1                          0
 6540                                 1                          0
 5765                                 1                          0
 6959                                 0                          0
 3108                                 1                          0

      payment_type_Credit card (automatic) payment_type_Electronic check  \
 3554                                    0                             1
 2063                                    1                             0
 1737                                    0                             1
 5894                                    0                             0
 209                                     0                             1
 ...                                   ...                           ...
 2529                                    0                             1
 6540                                    1                             0
 5765                                    0                             0
 6959                                    1                             0
 3108                                    0                             0

      payment_type_Mailed check
 3554                         0
 2063                         0
 1737                         0
 5894                         0
 209                          0
 ...                        ...
 2529                         0
 6540                         0
 5765                         0
 6959                         0
 3108                         0

 [1409 rows x 36 columns],
       gender  senior_citizen partner dependents  tenure phone_service  \
 3160  Female               0     Yes        Yes      51           Yes
 1577  Female               0     Yes         No      65           Yes
 6823  Female               0      No         No      18           Yes
 3615    Male               0      No         No      25           Yes
 882   Female               1      No         No       4           Yes
 ...      ...             ...     ...        ...     ...           ...
 1097  Female               0      No         No       2           Yes
 6441    Male               0      No         No       1           Yes
 5985  Female               0      No         No      67           Yes
 2452    Male               0     Yes        Yes      72            No
 983     Male               0      No         No      11           Yes

      multiple_lines online_security online_backup device_protection  ...  \
 3160            Yes             Yes            No                No  ...
 1577             No             Yes           Yes               Yes  ...
 6823             No             Yes            No                No  ...
 3615             No             Yes            No               Yes  ...
 882             Yes              No            No               Yes  ...
 ...             ...             ...           ...               ...  ...
 1097             No              No            No               Yes  ...
 6441             No              No            No                No  ...
 5985            Yes              No            No                No  ...
 2452             No             Yes           Yes               Yes  ...
 983              No              No           Yes                No  ...

      online_security_Yes online_backup_Yes device_protection_Yes  \
 3160                   1                 0                     0
 1577                   1                 1                     1
 6823                   1                 0                     0
 3615                   1                 0                     1
 882                    0                 0                     1
 ...                  ...               ...                   ...
 1097                   0                 0                     1
 6441                   0                 0                     0
 5985                   0                 0                     0
 2452                   1                 1                     1
 983                    0                 1                     0

      streaming_tv_Yes  paperless_billing_Yes  \
 3160                1                      1
 1577                0                      0
 6823                1                      1
 3615                1                      1
 882                 0                      1
 ...               ...                    ...
 1097                1                      0
 6441                0                      1
 5985                0                      1
 2452                0                      0
 983                 0                      1

      internet_service_type_Fiber optic internet_service_type_None  \
 3160                                 1                          0
 1577                                 0                          0
 6823                                 1                          0
 3615                                 1                          0
 882                                  1                          0
 ...                                ...                        ...
 1097                                 0                          0
 6441                                 0                          0
 5985                                 0                          1
 2452                                 0                          0
 983                                  1                          0

      payment_type_Credit card (automatic) payment_type_Electronic check  \
 3160                                    0                             0
 1577                                    0                             0
 6823                                    0                             1
 3615                                    0                             1
 882                                     0                             1
 ...                                   ...                           ...
 1097                                    0                             1
 6441                                    0                             0
 5985                                    0                             0
 2452                                    1                             0
 983                                     0                             1

      payment_type_Mailed check
 3160                         1
 1577                         0
 6823                         0
 3615                         0
 882                          0
 ...                        ...
 1097                         0
 6441                         1
 5985                         0
 2452                         0
 983                          0

 [1409 rows x 36 columns])

In [4]:
prep.get_prep_split_titanic()

(     passenger_id  survived  pclass     sex  sibsp  parch      fare embarked  \
 455           455         1       3    male      0      0    7.8958        C
 380           380         1       1  female      0      0  227.5250        C
 492           492         0       1    male      0      0   30.5000        S
 55             55         1       1    male      0      0   35.5000        S
 243           243         0       3    male      0      0    7.1250        S
 ..            ...       ...     ...     ...    ...    ...       ...      ...
 695           695         0       2    male      0      0   13.5000        S
 128           128         1       3  female      1      1   22.3583        C
 636           636         0       3    male      0      0    7.9250        S
 222           222         0       3    male      0      0    8.0500        S
 496           496         1       1  female      1      0   78.2667        C

      alone  sex_male  embarked_Q  embarked_S
 455      1         1           0           0
 380      1         0           0           0
 492      1         1           0           1
 55       1         1           0           1
 243      1         1           0           1
 ..     ...       ...         ...         ...
 695      1         1           0           1
 128      0         0           0           0
 636      1         1           0           1
 222      1         1           0           1
 496      0         0           0           0

 [534 rows x 12 columns],
      passenger_id  survived  pclass     sex  sibsp  parch     fare embarked  \
 176           176         0       3    male      3      1  25.4667        S
 372           372         0       3    male      0      0   8.0500        S
 678           678         0       3  female      1      6  46.9000        S
 778           778         0       3    male      0      0   7.7375        Q
 463           463         0       2    male      0      0  13.0000        S
 ..            ...       ...     ...     ...    ...    ...      ...      ...
 622           622         1       3    male      1      1  15.7417        C
 302           302         0       3    male      0      0   0.0000        S
 518           518         1       2  female      1      0  26.0000        S
 765           765         1       1  female      1      0  77.9583        S
 837           837         0       3    male      0      0   8.0500        S

      alone  sex_male  embarked_Q  embarked_S
 176      0         1           0           1
 372      1         1           0           1
 678      0         0           0           1
 778      1         1           1           0
 463      1         1           0           1
 ..     ...       ...         ...         ...
 622      0         1           0           0
 302      1         1           0           1
 518      0         0           0           1
 765      0         0           0           1
 837      1         1           0           1

 [178 rows x 12 columns],
      passenger_id  survived  pclass     sex  sibsp  parch      fare embarked  \
 561           561         0       3    male      0      0    7.8958        S
 641           641         1       1  female      0      0   69.3000        C
 400           400         1       3    male      0      0    7.9250        S
 498           498         0       1  female      1      2  151.5500        S
 875           875         1       3  female      0      0    7.2250        C
 ..            ...       ...     ...     ...    ...    ...       ...      ...
 339           339         0       1    male      0      0   35.5000        S
 841           841         0       2    male      0      0   10.5000        S
 442           442         0       3    male      1      0    7.7750        S
 815           815         0       1    male      0      0    0.0000        S
 53             53         1       2  female      1      0   26.0000        S

      alone  sex_male  embarked_Q  embarked_S
 561      1         1           0           1
 641      1         0           0           0
 400      1         1           0           1
 498      0         0           0           1
 875      1         0           0           0
 ..     ...       ...         ...         ...
 339      1         1           0           1
 841      1         1           0           1
 442      0         1           0           1
 815      1         1           0           1
 53       0         0           0           1

 [179 rows x 12 columns])